// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel TensorToTexture

StructuredBuffer<float3> InputTensor;
RWTexture2D<float4> OutputTexture;

[numthreads(8,8,1)]
void TensorToTexture (uint2 tid : SV_DispatchThreadID)
{
    float w, h;
    OutputTexture.GetDimensions(w, h);

    uint gid = (h - tid.y) * w + tid.x;
    float3 c = InputTensor[gid];
    OutputTexture[tid] = float4(c.x, c.y, c.z, 1.0);
}
