// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel LabelToTex

struct Label
{
    float scores[2];
};

StructuredBuffer<Label> LabelBuffer;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void LabelToTex (uint2 tid : SV_DispatchThreadID)
{
    uint gid = (128 - tid.y) * 128 + tid.x;
    Label label = LabelBuffer[gid];
    float4 c = float4(label.scores[0], label.scores[1], 0.0, 1.0);
    Result[tid] = c;
}
