// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel LabelToTex

uint Width;
uint Height;
StructuredBuffer<float2> LabelBuffer;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void LabelToTex (uint2 tid : SV_DispatchThreadID)
{
    uint gid = (Height - 1 - tid.y) * Width + tid.x;
    float2 label = LabelBuffer[gid];
    Result[tid] = float4(label.x, label.y, 0.0, 1.0);
}

